name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test log
        run: |
          echo "Hola git actions"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - run: npm install
      - run: npm run start
      - run: |
          git config user.name luisangelescom
          git config user.email luis20.lgi@gmail.com
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
          git push origin master
